/*
* generated by Xtext
*/
package org.example.entities.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider
import org.example.entities.entities.Attribute

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
class EntitiesOutlineTreeProvider extends DefaultOutlineTreeProvider {
	def _isLeaf(Attribute a) {
		true
	}
}
